FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./

# Restore as distinct layers
RUN dotnet restore demo
# Build and publish a release
RUN dotnet publish demo -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:6.0

WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "demo.dll"]