name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Restore dependencies
      run: dotnet restore test/
    - name: Build
      run: dotnet build test/ --no-restore
    - name: Test
      run: dotnet test test/ --no-build --verbosity normal